version: '3.8'
services:
  web:
    build: .
    container_name: postette_app
    ports:
      - "8000:8000"
    volumes:
      - ./instance:/app/instance
      - ./app/static/uploads:/app/app/static/uploads
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app
    restart: unless-stopped 