"""Add archived field to Post model

Revision ID: 0e038bf5848c
Revises: 92536ddb9ab4
Create Date: 2025-06-14 14:49:57.541443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e038bf5848c'
down_revision = '92536ddb9ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
