"""Add video_filenames column to Post model

Revision ID: 2d7b41eb9064
Revises: 531bcc0f0549
Create Date: 2025-06-17 11:03:25.312686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7b41eb9064'
down_revision = '531bcc0f0549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_filenames', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('video_filenames')

    # ### end Alembic commands ###
