"""Add verification fields to Subscriber model

Revision ID: 92536ddb9ab4
Revises: eea2c67f266d
Create Date: 2025-06-13 11:21:25.419048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92536ddb9ab4'
down_revision = 'eea2c67f266d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('unsubscribe_token',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_subscriber_verification_token', ['verification_token'])
        batch_op.drop_column('subscribed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('uq_subscriber_verification_token', type_='unique')
        batch_op.alter_column('unsubscribe_token',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###
